version: "3"

services:
  server:
    build: Server/
    command: python ./serverside.py
    hostname: promptserver
    environment: 
      - HOSTNAME=promptserver

  client1:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=1
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client2:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=2
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client3:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=3
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client4:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment:
      - CLIENT_ID=4
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client5:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=5
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client6:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=6
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client7:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=7
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client8:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=8
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client9:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=9
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client10:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=10
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client11:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=11
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

  client12:
    build: Client/
    command: python ./clientside.py
    volumes:
      - /home/sohlost/Projects/DaSH-Lab-Assignment-2024/DevelopmentAssignment/Level3/Client:/client
    environment: 
      - CLIENT_ID=12
      - HOSTNAME=promptserver
      - INPUT_DIR=/client/data
    depends_on:
      - server

